spring:
  application:
    name: erdb

  port: 8080

  config:
    import: ./secrets.properties

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_CONNECTION_URL}/${POSTGRES_DATABASE_NAME}
    username: ${POSTGRES_DATABASE_USERNAME}
    password: ${POSTGRES_DATABASE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl_auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mustache:
    charset=utf-8:

  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


logging:
  level:
    root: INFO

